// Indian Railways Asset & Defect Taxonomy by Department (Aligned with Fitted Preprocessing Pipeline)
export const DEPARTMENT_DATA = {
  "S&T": {
    assets: [
      "Colour Light Signal",
      "Track Circuit",
      "Interlocked Level Crossing",
      "Axle Counter",
      "Point Machine",
      "Electronic Interlocking"
    ],
    defects: [
      "LED aspect partial failure",
      "signal dark/intermittent",
      "insulation degradation",
      "gate detection fault",
      "aspect colour abnormality",
      "incorrect aspect indication",
      "evaluator communication fault",
      "mechanical wear",
      "count mismatch",
      "false occupancy",
      "communication redundancy loss",
      "boom locking fault",
      "reset recurrence",
      "motor current abnormality",
      "locking obstruction",
      "detection failure",
      "warning indication fault",
      "route setting anomaly",
      "loss of shunt",
      "I/O module fault"
    ],
    safety_functions: [
      "movement authority indication",
      "route locking and conflict prevention",
      "road-rail protection",
      "direct train running safety",
      "route setting and derailment prevention"
    ]
  },
  "Engineering": {
    assets: [
      "Bridge/Culvert",
      "Points & Crossing",
      "Sleeper/Fastening Zone",
      "Ballast/Formation Zone",
      "Rail/Track Section",
      "Level Crossing Surface"
    ],
    defects: [
      "structural crack indication",
      "switch rail gap",
      "missing/loose fastening",
      "broken sleeper cluster",
      "formation settlement",
      "crossing nose wear",
      "surface shelling/squat",
      "bearing distress",
      "road surface degradation",
      "drainage blockage",
      "poor drainage",
      "corrugation/wear",
      "ballast fouling",
      "rail crack indication",
      "sleeper cracking",
      "weld defect",
      "flange-way obstruction",
      "scour/erosion concern",
      "point misalignment",
      "approach settlement",
      "stretcher bar wear"
    ],
    safety_functions: [
      "structural route continuity",
      "route setting and derailment prevention",
      "gauge maintenance and load distribution",
      "track stability and drainage",
      "direct train running safety",
      "road-rail interface"
    ]
  },
  "Traction": {
    assets: [
      "Cantilever Assembly",
      "OHE Contact/Catenary",
      "Section Insulator",
      "Circuit Breaker/Interrupter",
      "Feeder/Return Conductor",
      "Traction Substation"
    ],
    defects: [
      "geometry deviation",
      "sag/height deviation",
      "flashover marks",
      "trip recurrence",
      "insulator chipping",
      "conductor damage",
      "cooling system degradation",
      "contact wire wear",
      "joint heating",
      "alignment deviation",
      "DGA anomaly",
      "insulator crack",
      "fitting looseness",
      "contact wear",
      "wire strand damage",
      "hot spot indication",
      "mechanism sluggishness",
      "connection looseness",
      "transformer alarm"
    ],
    safety_functions: [
      "OHE geometry",
      "traction power continuity",
      "electrical sectioning",
      "short circuit interruption",
      "traction return continuity",
      "grid feeding"
    ]
  }
};

export const SEVERITY_LEVELS = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];

export const MAINTENANCE_FREQUENCIES = [
  "Daily",
  "Weekly",
  "Fortnightly",
  "Monthly",
  "Quarterly",
  "Half-Yearly",
  "Annual"
];

export const RAILWAY_ZONES = [
  "NR", "WR", "CR", "ECoR", "SCR", "SR", "NCR", "ER",
  "SER", "SECR", "SWR", "WCR", "NER", "NFR", "ECR", "KR", "NWR"
];

// Test case presets (including real samples from 10k Master Pilot Dataset)
export const PRESETS = {
  highRiskST: {
    name: "1. High-Risk S&T (Signal LED / Axle Counter)",
    description: "Signal aspect failure with critical severity, 10-day overdue maintenance, and heavy daily train traffic.",
    data: {
      task_id: "TSK-IR-HIGH-01",
      asset_id: "AST-001238",
      department: "S&T",
      asset_type: "Colour Light Signal",
      safety_function: "movement authority indication",
      zone: "NCR",
      state: "Madhya Pradesh",
      asset_age_years: 8.4,
      asset_criticality: "CRITICAL",
      defect_type: "LED aspect partial failure",
      defect_severity: "CRITICAL",
      defect_severity_label: "CRITICAL",
      num_open_defects: 2,
      days_since_defect: 7,
      days_overdue: 10,
      maintenance_overdue_days: 10,
      maintenance_frequency: "Monthly",
      maintenance_interval_days: 30,
      days_since_last_maintenance: 45,
      previous_failures: 5,
      failures_last_12_months: 4,
      failures_last_365d: 4,
      failures_last_90d: 2,
      failures_last_30d: 1,
      same_defect_recurrences_365d: 2,
      trains_per_day: 65,
      scheduled_services_count_proxy: 65,
      goods_trains_per_day: 20,
      affected_services_if_blocked: 20,
      traffic_percentile: 0.85,
      operational_impact: "HIGH",
      operational_impact_score: 75.0,
      asset_criticality_score: 85.0,
      network_neighbor_degree: 4,
      alternative_route_available: 0,
      inspection_image_available: 1,
      maintenance_duration_hours: 2.5
    }
  },
  highRiskBridge: {
    name: "2. Real Pilot: Bridge Structural Crack (ECoR)",
    description: "Actual Pilot Dataset Row #2 (EVT-0000002): Girder bridge structural crack with 111-day overdue window.",
    data: {
      task_id: "EVT-0000002",
      asset_id: "AST-001877",
      department: "Engineering",
      asset_type: "Bridge/Culvert",
      safety_function: "structural route continuity",
      zone: "ECoR",
      state: "Orissa",
      asset_age_years: 8.0,
      asset_criticality: "HIGH",
      defect_type: "structural crack indication",
      defect_severity: "HIGH",
      defect_severity_label: "HIGH",
      num_open_defects: 2,
      days_since_defect: 7,
      days_overdue: 111,
      maintenance_overdue_days: 111,
      maintenance_frequency: "Quarterly",
      maintenance_interval_days: 90,
      days_since_last_maintenance: 201,
      previous_failures: 0,
      failures_last_12_months: 0,
      failures_last_365d: 0,
      failures_last_90d: 0,
      failures_last_30d: 0,
      same_defect_recurrences_365d: 0,
      trains_per_day: 34,
      scheduled_services_count_proxy: 34,
      goods_trains_per_day: 20,
      affected_services_if_blocked: 20,
      traffic_percentile: 0.548,
      operational_impact: "HIGH",
      operational_impact_score: 50.3,
      asset_criticality_score: 64.5,
      network_neighbor_degree: 4,
      alternative_route_available: 1,
      inspection_image_available: 1,
      maintenance_duration_hours: 8.18
    }
  },
  tractionRisk: {
    name: "3. Medium-Risk Traction (Contact Wire Wear)",
    description: "OHE Contact / Catenary wire section with contact wear, 15 overdue days, and moderate traffic.",
    data: {
      task_id: "TSK-IR-TRAC-03",
      asset_id: "AST-TRC-01142",
      department: "Traction",
      asset_type: "OHE Contact/Catenary",
      safety_function: "traction power continuity",
      zone: "WR",
      state: "Maharashtra",
      asset_age_years: 6.5,
      asset_criticality: "HIGH",
      defect_type: "contact wire wear",
      defect_severity: "MEDIUM",
      defect_severity_label: "MEDIUM",
      num_open_defects: 1,
      days_since_defect: 12,
      days_overdue: 15,
      maintenance_overdue_days: 15,
      maintenance_frequency: "Monthly",
      maintenance_interval_days: 30,
      days_since_last_maintenance: 45,
      previous_failures: 2,
      failures_last_12_months: 2,
      failures_last_365d: 2,
      failures_last_90d: 1,
      failures_last_30d: 0,
      same_defect_recurrences_365d: 1,
      trains_per_day: 70,
      scheduled_services_count_proxy: 70,
      goods_trains_per_day: 25,
      affected_services_if_blocked: 25,
      traffic_percentile: 0.72,
      operational_impact: "MEDIUM",
      operational_impact_score: 55.0,
      asset_criticality_score: 70.0,
      network_neighbor_degree: 3,
      alternative_route_available: 1,
      inspection_image_available: 1,
      maintenance_duration_hours: 3.5
    }
  },
  lowRiskRoutine: {
    name: "4. Low-Risk Routine Track Inspection (WR)",
    description: "Young PSC Sleeper/Fastening Zone with minor fastening looseness and zero overdue days.",
    data: {
      task_id: "TSK-IR-LOW-04",
      asset_id: "AST-ENG-01632",
      department: "Engineering",
      asset_type: "Sleeper/Fastening Zone",
      safety_function: "gauge maintenance and load distribution",
      zone: "WR",
      state: "Gujarat",
      asset_age_years: 2.0,
      asset_criticality: "LOW",
      defect_type: "missing/loose fastening",
      defect_severity: "LOW",
      defect_severity_label: "LOW",
      num_open_defects: 0,
      days_since_defect: 2,
      days_overdue: 0,
      maintenance_overdue_days: 0,
      maintenance_frequency: "Quarterly",
      maintenance_interval_days: 90,
      days_since_last_maintenance: 20,
      previous_failures: 0,
      failures_last_12_months: 0,
      failures_last_365d: 0,
      failures_last_90d: 0,
      failures_last_30d: 0,
      same_defect_recurrences_365d: 0,
      trains_per_day: 30,
      scheduled_services_count_proxy: 30,
      goods_trains_per_day: 6,
      affected_services_if_blocked: 6,
      traffic_percentile: 0.35,
      operational_impact: "LOW",
      operational_impact_score: 20.0,
      asset_criticality_score: 38.0,
      network_neighbor_degree: 2,
      alternative_route_available: 1,
      inspection_image_available: 1,
      maintenance_duration_hours: 1.5
    }
  },
  customTurnout: {
    name: "5. Turnout / Points & Crossing Switch Gap",
    description: "Heavy freight junction turnout with switch rail gap and 18-day overdue window.",
    data: {
      task_id: "TSK-IR-TURNOUT-05",
      asset_id: "AST-ENG-02878",
      department: "Engineering",
      asset_type: "Points & Crossing",
      safety_function: "route setting and derailment prevention",
      zone: "CR",
      state: "Maharashtra",
      asset_age_years: 7.5,
      asset_criticality: "CRITICAL",
      defect_type: "switch rail gap",
      defect_severity: "HIGH",
      defect_severity_label: "HIGH",
      num_open_defects: 2,
      days_since_defect: 14,
      days_overdue: 18,
      maintenance_overdue_days: 18,
      maintenance_frequency: "Monthly",
      maintenance_interval_days: 30,
      days_since_last_maintenance: 48,
      previous_failures: 3,
      failures_last_12_months: 2,
      failures_last_365d: 2,
      failures_last_90d: 1,
      failures_last_30d: 1,
      same_defect_recurrences_365d: 1,
      trains_per_day: 95,
      scheduled_services_count_proxy: 95,
      goods_trains_per_day: 40,
      affected_services_if_blocked: 40,
      traffic_percentile: 0.88,
      operational_impact: "CRITICAL",
      operational_impact_score: 88.0,
      asset_criticality_score: 85.0,
      network_neighbor_degree: 5,
      alternative_route_available: 0,
      inspection_image_available: 1,
      maintenance_duration_hours: 4.0
    }
  }
};
