import os
import sys
import json
import pandas as pd
import shutil

# Add ml to path
ml_dir = r"c:\Users\acous\Desktop\sih2026\ml"
sys.path.insert(0, ml_dir)

from backend.asset_service import AssetRegistryService

export_dir = r"c:\Users\acous\Desktop\sih2026\tejas_data_exports"

print("Starting export process...")

# 1. Load Registry and Export
service = AssetRegistryService()
service.load_registry()

assets = list(service.asset_registry.values())
df_registry = pd.DataFrame(assets)

registry_csv_path = os.path.join(export_dir, "ACTIVE_ASSET_REGISTRY.csv")
registry_json_path = os.path.join(export_dir, "ACTIVE_ASSET_REGISTRY.json")

df_registry.to_csv(registry_csv_path, index=False)
with open(registry_json_path, "w", encoding="utf-8") as f:
    json.dump(assets, f, indent=4)

print(f"Exported {len(df_registry)} assets to registry files.")

# 2. Training Dataset
training_src = os.path.join(ml_dir, "data", "tejas_pilot_master_dataset.csv")
training_dest = os.path.join(export_dir, "TEJAS_TRAINING_DATASET.csv")
shutil.copy2(training_src, training_dest)

print("Copied training dataset.")

# Also get train/test/val stats from processed
train_csv = os.path.join(ml_dir, "data", "processed", "train.csv")
test_csv = os.path.join(ml_dir, "data", "processed", "test.csv")
val_csv = os.path.join(ml_dir, "data", "processed", "validation.csv")

# 3 & 4 Generate DATA_INVENTORY.md
md_content = """# TEJAS DATA INVENTORY

This document provides a complete inventory of the datasets currently used by the TEJAS system.

## 1. Asset Registry (Backend)
- **File Name/Path:** `ACTIVE_ASSET_REGISTRY.csv` (and `.json`)
- **Original Source:** Extracted from `tejas_pilot_master_dataset.csv` grouped by `asset_id`
- **Purpose:** The ACTIVE, currently-running database of all physical railway assets known to the system. Used by the backend for resolving officer reports to full physical, topological, and historical maintenance metrics.
- **Number of Assets/Rows:** {registry_rows}
- **Data Type:** Derived (Computed state of assets from historical maintenance logs)
- **Columns:**
  - {registry_cols}

## 2. ML Training Dataset (Master)
- **File Name/Path:** `TEJAS_TRAINING_DATASET.csv` (Copy of `ml/data/tejas_pilot_master_dataset.csv`)
- **Purpose:** The master dataset used for training the models. Contains all maintenance events, failure logs, and computed risk indicators.
- **Number of Rows:** {training_rows}
- **Data Type:** Synthetic/Derived (Generated by `ml/data_generation/generate_dataset.py` simulating Indian Railways infrastructure)
- **Columns:**
  - {training_cols}

## 3. Raw Data Sources
- **`datameet_stations.json` & `datameet_trains.json` (ml/data/raw/)**
  - **Purpose:** GIS coordinates and zone/state mapping for railway stations.
  - **Data Type:** Real (Open data from DataMeet).
  - **Relationship:** Backend joins `station_code` in asset registry to these JSON files to append geographic metadata.
- **`hf_indian_railway_maintenance_sample.csv` (ml/data/raw/)**
  - **Purpose:** Open source Indian Railway historical maintenance sample.
  - **Data Type:** Real/Sample.
- **`indian_railways_traffic_stats.json` & `mendeley_track_faults_meta.json` (ml/data/sources/)**
  - **Purpose:** Traffic density parameters and track fault distribution baselines used during synthetic data generation.
  - **Data Type:** Real aggregated statistics.

## 4. Processed Model Splits
- **`train.csv` / `validation.csv` / `test.csv` (ml/data/processed/)**
  - **Purpose:** Splitted data used during hyperparameter tuning and model evaluation.
  - **Number of Rows:** Train ({train_rows}), Validation ({val_rows}), Test ({test_rows})
  - **Data Type:** Derived splits from the master training dataset.

## Dataset Relationships & Keys
- **`asset_id`**: The primary key that connects the Asset Registry to the Training Dataset. 
  - Every row in the training dataset (`TEJAS_TRAINING_DATASET.csv`) represents a specific maintenance event or snapshot in time for an `asset_id`.
  - The Asset Registry (`ACTIVE_ASSET_REGISTRY.csv`) contains precisely 1 row per unique `asset_id`, representing the *latest known operational state* computed from the training dataset logs.
- **`station_code`**: Connects assets to the real GIS databases (`datameet_stations.json`), bringing real-world Zone, State, and coordinates into the generated dataset and backend resolution.
"""

df_train = pd.read_csv(training_src)

def fmt_cols(df):
    return "\n  - ".join(list(df.columns)).strip()

df_tr = pd.read_csv(train_csv) if os.path.exists(train_csv) else []
df_val = pd.read_csv(val_csv) if os.path.exists(val_csv) else []
df_te = pd.read_csv(test_csv) if os.path.exists(test_csv) else []

final_md = md_content.format(
    registry_rows=len(df_registry),
    registry_cols=fmt_cols(df_registry),
    training_rows=len(df_train),
    training_cols=fmt_cols(df_train),
    train_rows=len(df_tr),
    val_rows=len(df_val),
    test_rows=len(df_te)
)

md_path = os.path.join(export_dir, "DATA_INVENTORY.md")
with open(md_path, "w", encoding="utf-8") as f:
    f.write(final_md)

print("Export completed successfully.")
